spring.application.name=Spring_MVC_11_MiniProject

#DataSource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=c##kamal1
spring.datasource.password=kamal

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

